FROM adopt openjdk/openjdk17:alpine

WORKDIR /app

COPY pom.xml .

RUN ./mvnw dependency:go-offline -B

COPY . .

RUN ./mvnw package -DskipTests

CMD ["java", "-jar", "target/ExpenseTrackerService-0.0.1-SNAPSHOT.jar"]
